apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskcluster
  labels:
    app: flaskcluster
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskcluster
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flaskcluster
    spec:
      containers:
        - image: greentropikal/covid19-analysis:latest
          imagePullPolicy: Always
          name: flaskcluster
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"